// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vehicle.proto
#ifndef GRPC_vehicle_2eproto__INCLUDED
#define GRPC_vehicle_2eproto__INCLUDED

#include "vehicle.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace vehicle {

class DataExchanger final {
 public:
  static constexpr char const* service_full_name() {
    return "vehicle.DataExchanger";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ManageSpeed(::grpc::ClientContext* context, const ::vehicle::SpeedAction& request, ::vehicle::NumberDataReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>> AsyncManageSpeed(::grpc::ClientContext* context, const ::vehicle::SpeedAction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>>(AsyncManageSpeedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>> PrepareAsyncManageSpeed(::grpc::ClientContext* context, const ::vehicle::SpeedAction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>>(PrepareAsyncManageSpeedRaw(context, request, cq));
    }
    virtual ::grpc::Status GetNumberData(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::vehicle::NumberDataReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>> AsyncGetNumberData(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>>(AsyncGetNumberDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>> PrepareAsyncGetNumberData(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>>(PrepareAsyncGetNumberDataRaw(context, request, cq));
    }
    virtual ::grpc::Status FillFuel(::grpc::ClientContext* context, const ::vehicle::FuelAmount& request, ::vehicle::FuelAmount* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>> AsyncFillFuel(::grpc::ClientContext* context, const ::vehicle::FuelAmount& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>>(AsyncFillFuelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>> PrepareAsyncFillFuel(::grpc::ClientContext* context, const ::vehicle::FuelAmount& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>>(PrepareAsyncFillFuelRaw(context, request, cq));
    }
    virtual ::grpc::Status GetTotalFuel(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::vehicle::FuelAmount* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>> AsyncGetTotalFuel(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>>(AsyncGetTotalFuelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>> PrepareAsyncGetTotalFuel(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>>(PrepareAsyncGetTotalFuelRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ManageSpeed(::grpc::ClientContext* context, const ::vehicle::SpeedAction* request, ::vehicle::NumberDataReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ManageSpeed(::grpc::ClientContext* context, const ::vehicle::SpeedAction* request, ::vehicle::NumberDataReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetNumberData(::grpc::ClientContext* context, const ::vehicle::Ping* request, ::vehicle::NumberDataReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetNumberData(::grpc::ClientContext* context, const ::vehicle::Ping* request, ::vehicle::NumberDataReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FillFuel(::grpc::ClientContext* context, const ::vehicle::FuelAmount* request, ::vehicle::FuelAmount* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FillFuel(::grpc::ClientContext* context, const ::vehicle::FuelAmount* request, ::vehicle::FuelAmount* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetTotalFuel(::grpc::ClientContext* context, const ::vehicle::Ping* request, ::vehicle::FuelAmount* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetTotalFuel(::grpc::ClientContext* context, const ::vehicle::Ping* request, ::vehicle::FuelAmount* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>* AsyncManageSpeedRaw(::grpc::ClientContext* context, const ::vehicle::SpeedAction& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>* PrepareAsyncManageSpeedRaw(::grpc::ClientContext* context, const ::vehicle::SpeedAction& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>* AsyncGetNumberDataRaw(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::NumberDataReply>* PrepareAsyncGetNumberDataRaw(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>* AsyncFillFuelRaw(::grpc::ClientContext* context, const ::vehicle::FuelAmount& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>* PrepareAsyncFillFuelRaw(::grpc::ClientContext* context, const ::vehicle::FuelAmount& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>* AsyncGetTotalFuelRaw(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::FuelAmount>* PrepareAsyncGetTotalFuelRaw(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ManageSpeed(::grpc::ClientContext* context, const ::vehicle::SpeedAction& request, ::vehicle::NumberDataReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>> AsyncManageSpeed(::grpc::ClientContext* context, const ::vehicle::SpeedAction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>>(AsyncManageSpeedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>> PrepareAsyncManageSpeed(::grpc::ClientContext* context, const ::vehicle::SpeedAction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>>(PrepareAsyncManageSpeedRaw(context, request, cq));
    }
    ::grpc::Status GetNumberData(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::vehicle::NumberDataReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>> AsyncGetNumberData(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>>(AsyncGetNumberDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>> PrepareAsyncGetNumberData(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>>(PrepareAsyncGetNumberDataRaw(context, request, cq));
    }
    ::grpc::Status FillFuel(::grpc::ClientContext* context, const ::vehicle::FuelAmount& request, ::vehicle::FuelAmount* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>> AsyncFillFuel(::grpc::ClientContext* context, const ::vehicle::FuelAmount& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>>(AsyncFillFuelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>> PrepareAsyncFillFuel(::grpc::ClientContext* context, const ::vehicle::FuelAmount& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>>(PrepareAsyncFillFuelRaw(context, request, cq));
    }
    ::grpc::Status GetTotalFuel(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::vehicle::FuelAmount* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>> AsyncGetTotalFuel(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>>(AsyncGetTotalFuelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>> PrepareAsyncGetTotalFuel(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>>(PrepareAsyncGetTotalFuelRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ManageSpeed(::grpc::ClientContext* context, const ::vehicle::SpeedAction* request, ::vehicle::NumberDataReply* response, std::function<void(::grpc::Status)>) override;
      void ManageSpeed(::grpc::ClientContext* context, const ::vehicle::SpeedAction* request, ::vehicle::NumberDataReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetNumberData(::grpc::ClientContext* context, const ::vehicle::Ping* request, ::vehicle::NumberDataReply* response, std::function<void(::grpc::Status)>) override;
      void GetNumberData(::grpc::ClientContext* context, const ::vehicle::Ping* request, ::vehicle::NumberDataReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FillFuel(::grpc::ClientContext* context, const ::vehicle::FuelAmount* request, ::vehicle::FuelAmount* response, std::function<void(::grpc::Status)>) override;
      void FillFuel(::grpc::ClientContext* context, const ::vehicle::FuelAmount* request, ::vehicle::FuelAmount* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetTotalFuel(::grpc::ClientContext* context, const ::vehicle::Ping* request, ::vehicle::FuelAmount* response, std::function<void(::grpc::Status)>) override;
      void GetTotalFuel(::grpc::ClientContext* context, const ::vehicle::Ping* request, ::vehicle::FuelAmount* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>* AsyncManageSpeedRaw(::grpc::ClientContext* context, const ::vehicle::SpeedAction& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>* PrepareAsyncManageSpeedRaw(::grpc::ClientContext* context, const ::vehicle::SpeedAction& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>* AsyncGetNumberDataRaw(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle::NumberDataReply>* PrepareAsyncGetNumberDataRaw(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>* AsyncFillFuelRaw(::grpc::ClientContext* context, const ::vehicle::FuelAmount& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>* PrepareAsyncFillFuelRaw(::grpc::ClientContext* context, const ::vehicle::FuelAmount& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>* AsyncGetTotalFuelRaw(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle::FuelAmount>* PrepareAsyncGetTotalFuelRaw(::grpc::ClientContext* context, const ::vehicle::Ping& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ManageSpeed_;
    const ::grpc::internal::RpcMethod rpcmethod_GetNumberData_;
    const ::grpc::internal::RpcMethod rpcmethod_FillFuel_;
    const ::grpc::internal::RpcMethod rpcmethod_GetTotalFuel_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ManageSpeed(::grpc::ServerContext* context, const ::vehicle::SpeedAction* request, ::vehicle::NumberDataReply* response);
    virtual ::grpc::Status GetNumberData(::grpc::ServerContext* context, const ::vehicle::Ping* request, ::vehicle::NumberDataReply* response);
    virtual ::grpc::Status FillFuel(::grpc::ServerContext* context, const ::vehicle::FuelAmount* request, ::vehicle::FuelAmount* response);
    virtual ::grpc::Status GetTotalFuel(::grpc::ServerContext* context, const ::vehicle::Ping* request, ::vehicle::FuelAmount* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ManageSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ManageSpeed() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ManageSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ManageSpeed(::grpc::ServerContext* /*context*/, const ::vehicle::SpeedAction* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestManageSpeed(::grpc::ServerContext* context, ::vehicle::SpeedAction* request, ::grpc::ServerAsyncResponseWriter< ::vehicle::NumberDataReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetNumberData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetNumberData() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetNumberData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNumberData(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNumberData(::grpc::ServerContext* context, ::vehicle::Ping* request, ::grpc::ServerAsyncResponseWriter< ::vehicle::NumberDataReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FillFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FillFuel() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_FillFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FillFuel(::grpc::ServerContext* /*context*/, const ::vehicle::FuelAmount* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFillFuel(::grpc::ServerContext* context, ::vehicle::FuelAmount* request, ::grpc::ServerAsyncResponseWriter< ::vehicle::FuelAmount>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetTotalFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetTotalFuel() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetTotalFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTotalFuel(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTotalFuel(::grpc::ServerContext* context, ::vehicle::Ping* request, ::grpc::ServerAsyncResponseWriter< ::vehicle::FuelAmount>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ManageSpeed<WithAsyncMethod_GetNumberData<WithAsyncMethod_FillFuel<WithAsyncMethod_GetTotalFuel<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ManageSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ManageSpeed() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle::SpeedAction, ::vehicle::NumberDataReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle::SpeedAction* request, ::vehicle::NumberDataReply* response) { return this->ManageSpeed(context, request, response); }));}
    void SetMessageAllocatorFor_ManageSpeed(
        ::grpc::MessageAllocator< ::vehicle::SpeedAction, ::vehicle::NumberDataReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle::SpeedAction, ::vehicle::NumberDataReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ManageSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ManageSpeed(::grpc::ServerContext* /*context*/, const ::vehicle::SpeedAction* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ManageSpeed(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle::SpeedAction* /*request*/, ::vehicle::NumberDataReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetNumberData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetNumberData() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle::Ping, ::vehicle::NumberDataReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle::Ping* request, ::vehicle::NumberDataReply* response) { return this->GetNumberData(context, request, response); }));}
    void SetMessageAllocatorFor_GetNumberData(
        ::grpc::MessageAllocator< ::vehicle::Ping, ::vehicle::NumberDataReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle::Ping, ::vehicle::NumberDataReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetNumberData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNumberData(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNumberData(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::NumberDataReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FillFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FillFuel() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle::FuelAmount, ::vehicle::FuelAmount>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle::FuelAmount* request, ::vehicle::FuelAmount* response) { return this->FillFuel(context, request, response); }));}
    void SetMessageAllocatorFor_FillFuel(
        ::grpc::MessageAllocator< ::vehicle::FuelAmount, ::vehicle::FuelAmount>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle::FuelAmount, ::vehicle::FuelAmount>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FillFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FillFuel(::grpc::ServerContext* /*context*/, const ::vehicle::FuelAmount* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FillFuel(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle::FuelAmount* /*request*/, ::vehicle::FuelAmount* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetTotalFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetTotalFuel() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle::Ping, ::vehicle::FuelAmount>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle::Ping* request, ::vehicle::FuelAmount* response) { return this->GetTotalFuel(context, request, response); }));}
    void SetMessageAllocatorFor_GetTotalFuel(
        ::grpc::MessageAllocator< ::vehicle::Ping, ::vehicle::FuelAmount>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle::Ping, ::vehicle::FuelAmount>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetTotalFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTotalFuel(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTotalFuel(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::FuelAmount* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ManageSpeed<WithCallbackMethod_GetNumberData<WithCallbackMethod_FillFuel<WithCallbackMethod_GetTotalFuel<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ManageSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ManageSpeed() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ManageSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ManageSpeed(::grpc::ServerContext* /*context*/, const ::vehicle::SpeedAction* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetNumberData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetNumberData() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetNumberData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNumberData(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FillFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FillFuel() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_FillFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FillFuel(::grpc::ServerContext* /*context*/, const ::vehicle::FuelAmount* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetTotalFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetTotalFuel() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetTotalFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTotalFuel(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ManageSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ManageSpeed() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ManageSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ManageSpeed(::grpc::ServerContext* /*context*/, const ::vehicle::SpeedAction* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestManageSpeed(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetNumberData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetNumberData() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetNumberData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNumberData(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNumberData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FillFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FillFuel() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_FillFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FillFuel(::grpc::ServerContext* /*context*/, const ::vehicle::FuelAmount* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFillFuel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetTotalFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetTotalFuel() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetTotalFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTotalFuel(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTotalFuel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ManageSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ManageSpeed() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ManageSpeed(context, request, response); }));
    }
    ~WithRawCallbackMethod_ManageSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ManageSpeed(::grpc::ServerContext* /*context*/, const ::vehicle::SpeedAction* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ManageSpeed(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetNumberData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetNumberData() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetNumberData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetNumberData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNumberData(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNumberData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FillFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FillFuel() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FillFuel(context, request, response); }));
    }
    ~WithRawCallbackMethod_FillFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FillFuel(::grpc::ServerContext* /*context*/, const ::vehicle::FuelAmount* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FillFuel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetTotalFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetTotalFuel() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetTotalFuel(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetTotalFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTotalFuel(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTotalFuel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ManageSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ManageSpeed() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle::SpeedAction, ::vehicle::NumberDataReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle::SpeedAction, ::vehicle::NumberDataReply>* streamer) {
                       return this->StreamedManageSpeed(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ManageSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ManageSpeed(::grpc::ServerContext* /*context*/, const ::vehicle::SpeedAction* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedManageSpeed(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle::SpeedAction,::vehicle::NumberDataReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetNumberData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetNumberData() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle::Ping, ::vehicle::NumberDataReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle::Ping, ::vehicle::NumberDataReply>* streamer) {
                       return this->StreamedGetNumberData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetNumberData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetNumberData(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::NumberDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetNumberData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle::Ping,::vehicle::NumberDataReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FillFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FillFuel() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle::FuelAmount, ::vehicle::FuelAmount>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle::FuelAmount, ::vehicle::FuelAmount>* streamer) {
                       return this->StreamedFillFuel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FillFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FillFuel(::grpc::ServerContext* /*context*/, const ::vehicle::FuelAmount* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFillFuel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle::FuelAmount,::vehicle::FuelAmount>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetTotalFuel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetTotalFuel() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle::Ping, ::vehicle::FuelAmount>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle::Ping, ::vehicle::FuelAmount>* streamer) {
                       return this->StreamedGetTotalFuel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetTotalFuel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetTotalFuel(::grpc::ServerContext* /*context*/, const ::vehicle::Ping* /*request*/, ::vehicle::FuelAmount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetTotalFuel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle::Ping,::vehicle::FuelAmount>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ManageSpeed<WithStreamedUnaryMethod_GetNumberData<WithStreamedUnaryMethod_FillFuel<WithStreamedUnaryMethod_GetTotalFuel<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ManageSpeed<WithStreamedUnaryMethod_GetNumberData<WithStreamedUnaryMethod_FillFuel<WithStreamedUnaryMethod_GetTotalFuel<Service > > > > StreamedService;
};

}  // namespace vehicle


#endif  // GRPC_vehicle_2eproto__INCLUDED
